### ISSUE TITLE
Creating Schedules automatically

### ISSUE THREAD

**Issue by rland93** [lukeren314/ZotDegree#9]
I started working on a project to automatically generate quarter-by-quarter course schedules. I think it'd be a great fit for integration into this project. Basically, I made a thing that:

- Scrapes courses from the master course listing https://catalogue.uci.edu/allcourses/
- For each course, get the requirements, corequirements, overlaps, unit count, and restrictions.
- That course becomes the vertex in a graph
- By traversing the graph, you can generate a plan to fulfill prereqs for a certain course.

So for the vertex MATH 107, we scrape the course listing:
```
MATH 107. Numerical Differential Equations. 4 Units.

Theory and applications of numerical methods to initial and boundary-value problems for ordinary and partial differential equations.

Corequisite: MATH 107L
Prerequisite: MATH 3D and MATH 105B
```
This goes in as a vertex called MATH 107, and has edges from MATH 3D and MATH 105B to it.

Then, if you want to take MATH 107, you need to have taken everything in a traversal of the tree rooted at MATH 107. 

Here's an example image from my program:

![https://i.ibb.co/HDKgtRB/math107.png](https://i.ibb.co/HDKgtRB/math107.png)

I got as far as being able to generate images of these trees, and I could generate rudimentary class plans by just traversing vertices with BFS, but the co-dependencies made it really difficult to generate actually viable course plans. I ran into many issues with scraping the dependency list properly (requirements are not semantically marked up!), parsing the dependencies, and traversing the graph with co-dependencies, as well as getting the trees to display in a neat way.

I think it will be doable to add this as a feature. 

I'm thinking that the user puts in all classes that he/she has taken, the max units they are willing to take per quarter, and then presses a button that will auto-populate the class plan with a BFS search on the vertices of this dependency graph for the list of major-required classes. For the straightforward majors (mostly math and engineering were the ones that I tested and found to be "easy") this would work well I think.

**Comment by lukeren314** [comment]
Howdy,
I think that's a super cool project/feature! I do agree that the feature is a lot more beneficial for straightforward majors where there is less flexibility in course choices, but I think even so, mapping out the first few lower-division classes for every major would be really helpful. Though to be completely honest, I don't plan on supporting this project (adding new features and such) any time in the near future. I've moved onto other projects/responsibilities that are more time consuming (as do many people working in open source, especially those doing it alone XP). There's lots of things that I still want to add, and even more things that I wish I had fixed to make adding features easier (looking back at the state management and component design makes me vomit a little). I don't think I can do more than review and merge pull requests at the moment, but I think it's super cool what you're doing and wish you the best! Who knows, maybe in a few months/years I'll revive the project with some friends and implement this feature. Or if you and some of your friends want to I'd be happy to pass it on 😉
